import { useEffect, useRef, type PointerEvent } from "react";
import { BALL_RADIUS, BRICK_HEIGHT, BRICK_LEFT, BRICK_TOP, BRICK_WIDTH, FIXED_STEP, KEYBOARD_SPEED, LOGICAL_HEIGHT, LOGICAL_WIDTH, PADDLE_HEIGHT, PADDLE_Y, SHIELD_Y, type KeeperBreakoutState } from "./keeperBreakoutEngine.js";
import { loadKeeperBreakoutAssets, type KeeperBreakoutAssets } from "./keeperBreakoutAssets.js";
export function KeeperBreakoutCanvas({ state, onAdvance, onPaddleTarget, onLaunch }: { state: KeeperBreakoutState; onAdvance: (dt: number) => void; onPaddleTarget: (x: number) => void; onLaunch: () => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const stateRef = useRef(state); const callbackRef = useRef({ onAdvance, onPaddleTarget, onLaunch }); const assets = useRef<KeeperBreakoutAssets>(); const heldKeys = useRef(new Set<string>()); const keyboardTarget = useRef(state.paddle.targetX); stateRef.current = state; callbackRef.current = { onAdvance, onPaddleTarget, onLaunch };
  useEffect(() => { let mounted = true; void loadKeeperBreakoutAssets().then((value) => { if (mounted) { assets.current = value; draw(); } }); return () => { mounted = false; }; }, []);
  useEffect(() => { const canvas = canvasRef.current; const context = canvas?.getContext("2d"); if (!canvas || !context) return; const resize = () => { const rect = canvas.getBoundingClientRect(); const dpr = window.devicePixelRatio || 1; canvas.width = Math.max(1, Math.round(rect.width * dpr)); canvas.height = Math.max(1, Math.round(rect.height * dpr)); context.setTransform(canvas.width / LOGICAL_WIDTH, 0, 0, canvas.height / LOGICAL_HEIGHT, 0, 0); draw(); }; resize(); const observer = new ResizeObserver(resize); observer.observe(canvas); return () => observer.disconnect(); }, []);
  useEffect(() => { draw(); }, [state]);
  useEffect(() => { if (!heldKeys.current.size) keyboardTarget.current = state.paddle.targetX; }, [state.paddle.targetX]);
  useEffect(() => { if (state.phase !== "playing") return; let frame = 0; let previous = performance.now(); let accumulator = 0; let hidden = document.hidden; const visibility = () => { hidden = document.hidden; previous = performance.now(); accumulator = 0; if (!hidden && !frame) frame = requestAnimationFrame(tick); }; const tick = (now: number) => { frame = 0; if (hidden) return; accumulator = Math.min(.2, accumulator + (now - previous) / 1000); previous = now; while (accumulator >= FIXED_STEP) { const direction = Number(heldKeys.current.has("ArrowRight")) - Number(heldKeys.current.has("ArrowLeft")); if (direction) { const paddle = stateRef.current.paddle; keyboardTarget.current = Math.max(paddle.w / 2, Math.min(LOGICAL_WIDTH - paddle.w / 2, keyboardTarget.current + direction * KEYBOARD_SPEED * FIXED_STEP)); callbackRef.current.onPaddleTarget(keyboardTarget.current); } callbackRef.current.onAdvance(FIXED_STEP); accumulator -= FIXED_STEP; } draw(); frame = requestAnimationFrame(tick); }; document.addEventListener("visibilitychange", visibility); if (!hidden) frame = requestAnimationFrame(tick); return () => { document.removeEventListener("visibilitychange", visibility); if (frame) cancelAnimationFrame(frame); }; }, [state.phase]);
  function draw() { const context = canvasRef.current?.getContext("2d"); if (!context) return; const game = stateRef.current; context.clearRect(0, 0, LOGICAL_WIDTH, LOGICAL_HEIGHT); const background = assets.current?.background; if (background) context.drawImage(background, 0, 0, LOGICAL_WIDTH, LOGICAL_HEIGHT); else { context.fillStyle = "#063d24"; context.fillRect(0, 0, LOGICAL_WIDTH, LOGICAL_HEIGHT); context.strokeStyle = "rgba(255,255,255,.16)"; context.lineWidth = 2; context.strokeRect(82, 35, 476, 340); context.beginPath(); context.arc(320, 410, 52, Math.PI, 0); context.stroke(); }
    for (const brick of game.bricks) { const x = BRICK_LEFT + brick.col * 60; const y = BRICK_TOP + brick.row * 24; const image = assets.current?.bricks[brick.type]; if (image) context.drawImage(image, x, y, BRICK_WIDTH, BRICK_HEIGHT); else { const color: Record<string, string> = { hp1: "#00e9ae", hp2: "#2a9dff", hp3: "#ff963f", gold: "#ffd44f", steel: "#718596", burst: "#f35f55" }; context.fillStyle = color[brick.type]; context.fillRect(x, y, BRICK_WIDTH, BRICK_HEIGHT); context.strokeStyle = "#10271d"; context.lineWidth = 2; context.strokeRect(x + 1, y + 1, BRICK_WIDTH - 2, BRICK_HEIGHT - 2); }
    }
    if (game.effects.shield) { context.strokeStyle = "rgba(195,255,237,.86)"; context.lineWidth = 2; context.setLineDash([7, 5]); context.beginPath(); context.moveTo(12, SHIELD_Y); context.lineTo(LOGICAL_WIDTH - 12, SHIELD_Y); context.stroke(); context.setLineDash([]); }
    for (const drop of game.drops) { const image = assets.current?.powerups[drop.kind]; if (image) context.drawImage(image, drop.x - 16, drop.y - 16, 32, 32); else { context.beginPath(); context.arc(drop.x, drop.y, 13, 0, Math.PI * 2); context.fillStyle = "#ffd44f"; context.fill(); context.fillStyle = "#10271d"; context.font = "900 13px sans-serif"; context.textAlign = "center"; context.textBaseline = "middle"; context.fillText(drop.kind[0].toUpperCase(), drop.x, drop.y); } }
    const paddleImage = game.paddle.w > 112 ? assets.current?.paddleWide : assets.current?.paddle; if (paddleImage) context.drawImage(paddleImage, game.paddle.x, PADDLE_Y, game.paddle.w, PADDLE_HEIGHT); else { context.fillStyle = "#00e9ae"; context.beginPath(); context.roundRect(game.paddle.x, PADDLE_Y, game.paddle.w, PADDLE_HEIGHT, 14); context.fill(); context.strokeStyle = "#10271d"; context.lineWidth = 2; context.stroke(); }
    for (const ball of game.balls) { const image = assets.current?.ball; if (image) context.drawImage(image, ball.x - BALL_RADIUS, ball.y - BALL_RADIUS, BALL_RADIUS * 2, BALL_RADIUS * 2); else { context.beginPath(); context.arc(ball.x, ball.y, BALL_RADIUS, 0, Math.PI * 2); context.fillStyle = "#f7faf6"; context.fill(); context.strokeStyle = "#10271d"; context.lineWidth = 1.5; context.stroke(); } }
  }
  const point = (event: PointerEvent<HTMLCanvasElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return (event.clientX - rect.left) * LOGICAL_WIDTH / rect.width; };
  return <canvas ref={canvasRef} className="keeper-breakout-canvas" aria-label="골키퍼 벽돌깨기 게임 영역" tabIndex={0} onPointerMove={(event) => { heldKeys.current.clear(); onPaddleTarget(point(event)); }} onPointerDown={(event) => { event.currentTarget.focus(); heldKeys.current.clear(); onPaddleTarget(point(event)); onLaunch(); }} onKeyDown={(event) => { if (event.key === " " || event.key === "Spacebar") { event.preventDefault(); if (!event.repeat) onLaunch(); return; } if (event.key === "ArrowLeft" || event.key === "ArrowRight") { event.preventDefault(); heldKeys.current.add(event.key); keyboardTarget.current = stateRef.current.paddle.targetX; } }} onKeyUp={(event) => { if (event.key === "ArrowLeft" || event.key === "ArrowRight") { event.preventDefault(); heldKeys.current.delete(event.key); } }} onBlur={() => heldKeys.current.clear()} />;
}
