import { Music4, Volume2, VolumeX } from "lucide-react";
import { Modal, useEscape } from "../../Modal.js";
import { NewGameButton } from "../NewGameButton.js";
import { SoundControl } from "../SoundControl.js";
import { MinigameStage } from "../ranking/MinigameStage.js";
import { RankingPanel } from "../ranking/RankingPanel.js";
import { useRanking } from "../ranking/useRanking.js";
import { loadKeeperBreakoutHighScore } from "../../storage.js";
import { KeeperBreakoutCanvas } from "./KeeperBreakoutCanvas.js";
import { useKeeperBreakoutGame, type KeeperBreakoutRoundResult } from "./useKeeperBreakoutGame.js";
import { useKeeperBreakoutMusic } from "./useKeeperBreakoutMusic.js";
import { useKeeperBreakoutSfx } from "./useKeeperBreakoutSfx.js";
import "./keeper-breakout.css";
export default function KeeperBreakoutModal({ onClose, onRoundEnd }: { onClose: () => void; onRoundEnd?: (result: KeeperBreakoutRoundResult) => void }) { useEscape(onClose); const sfx = useKeeperBreakoutSfx(); const music = useKeeperBreakoutMusic(); const ranking = useRanking("keeper-breakout", () => loadKeeperBreakoutHighScore() || null); const game = useKeeperBreakoutGame({ sfxOn: sfx.sfxOn, sfxVolume: sfx.sfxVolume, onRoundEnd: (result) => { music.stopMusic(); onRoundEnd?.(result); ranking.report(result.score); } }); const start = () => { game.start(); music.startMusic(); }; const newGame = () => { ranking.abandon(); start(); }; const ended = game.state.phase === "over" || game.state.phase === "cleared"; return <Modal onClose={onClose} label="골키퍼 벽돌깨기" wide header={<div><p className="eyebrow">MINIGAME</p><h2 className="keeper-breakout__title"><span aria-hidden="true">🧤</span> 골키퍼 벽돌깨기</h2><p className="keeper-breakout__intro">골키퍼 장갑으로 축구공을 쳐서 광고판을 모두 깨세요.</p></div>}><MinigameStage panel={<RankingPanel {...ranking.panel} />}><div className="keeper-breakout-meta"><div className="keeper-breakout-hud"><span className="keeper-breakout-badge">스테이지 {game.state.stage + 1}/5</span><span className="keeper-breakout-badge">점수 {game.state.score}</span><span className="keeper-breakout-badge">최고 {game.highScore}</span><span className="keeper-breakout-badge">목숨 {"⚽".repeat(game.state.lives)}</span></div><SoundControl enabled={music.musicOn} volume={music.musicVolume} onToggle={music.toggleMusic} onVolumeChange={music.changeMusicVolume} icon={<Music4 aria-hidden="true" />} label="배경음악" wrapperClassName="keeper-breakout-icon-toggle"/><SoundControl enabled={sfx.sfxOn} volume={sfx.sfxVolume} onToggle={sfx.toggleSfx} onVolumeChange={sfx.changeSfxVolume} icon={sfx.sfxOn ? <Volume2 aria-hidden="true" /> : <VolumeX aria-hidden="true" />} label="효과음" wrapperClassName="keeper-breakout-icon-toggle"/><NewGameButton onNewGame={newGame} hidden={game.state.phase !== "playing" && game.state.phase !== "stageclear"} /></div><div className="keeper-breakout-play-area"><KeeperBreakoutCanvas state={game.state} onAdvance={game.advance} onPaddleTarget={game.setPaddleTarget} onLaunch={game.launch}/>{game.state.phase === "ready" && <div className="keeper-breakout-start-panel"><strong>장갑을 준비하세요!</strong><span>마우스 또는 키보드 ←/→로 이동하고, 클릭 또는 Space로 발사합니다.</span><button type="button" className="keeper-breakout-start" onClick={start}>게임 시작</button></div>}{ended && <div className="keeper-breakout-result" role="status"><strong>{game.state.phase === "cleared" ? "전 스테이지 클리어!" : "경기 종료!"}</strong><span>{game.state.score}점 획득 {game.state.score === game.highScore && game.state.score > 0 ? "· 최고 기록!" : ""}</span><button type="button" className="keeper-breakout-start" onClick={start}>다시 시작</button></div>}</div></MinigameStage></Modal>; }
