import { useCallback, useEffect, useRef, useState, type PointerEvent } from "react";
import { type Board, type FootballMatch3State, type Step, type Tile } from "./footballMatch3Engine.js";
import { loadFootballMatch3Assets, type FootballMatch3Assets } from "./footballMatch3Assets.js";

const COLORS = ["#f7f7f2", "#00e9ae", "#ff8738", "#f3c84e", "#357cfd", "#ef4855"];
const LABELS = ["공", "유", "화", "휘", "장", "카"];
// Measured against the board frame's clear opening. The outer grid always clears its mint trim.
const GRID_ORIGIN = 74;
const CELL_SIZE = 45;
const findHint = (_engine: FootballMatch3State): undefined => undefined;
const copy = (board: Board) => board.map((tile) => tile && { ...tile });
const point = (index: number) => ({ x: GRID_ORIGIN + index % 8 * CELL_SIZE, y: GRID_ORIGIN + Math.floor(index / 8) * CELL_SIZE });

export function FootballMatch3Canvas({ engine, animationBoard, steps, invalidSwap, disabled, onTryMove, onClearStep, onAnimationEnd }: { engine: FootballMatch3State; animationBoard: Board; steps: Step[]; invalidSwap?: [number, number]; disabled: boolean; onTryMove: (a: number, b: number) => void; onClearStep: (step: Step) => void; onAnimationEnd: () => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const assets = useRef<FootballMatch3Assets | null>(null); const shown = useRef<Board>(copy(engine.board)); const moving = useRef<{ from: number; to: number; tile: Tile; progress: number }[]>([]); const selected = useRef<number | null>(null); const pointer = useRef<number | null>(null); const [cursor, setCursor] = useState(0); const drawRef = useRef<() => void>(() => {});
  const draw = useCallback(() => { const canvas = canvasRef.current; const context = canvas?.getContext("2d"); if (!canvas || !context) return; const art = assets.current; context.clearRect(-200, 0, 912, 512); if (art?.background) context.drawImage(art.background, 0, 0, 512, 512); else { context.fillStyle = "#063d24"; context.fillRect(0, 0, 512, 512); } context.fillStyle = "rgba(1,25,16,.5)"; context.fillRect(36, 36, 440, 440); const active = new Set(moving.current.map((item) => item.from)); const tile = (value: Tile, x: number, y: number) => { const image = value.kind === "golden" ? art?.golden : art?.tiles[value.color]; context.fillStyle = "rgba(255,255,255,.1)"; context.fillRect(x + 2, y + 2, 48, 48); if (image) context.drawImage(image, x + 3, y + 3, 46, 46); else { context.beginPath(); context.arc(x + 26, y + 26, 18, 0, Math.PI * 2); context.fillStyle = value.kind === "golden" ? "#ffd44f" : COLORS[value.color]; context.fill(); context.strokeStyle = "#10271d"; context.lineWidth = 3; context.stroke(); context.fillStyle = "#10271d"; context.font = "800 18px sans-serif"; context.textAlign = "center"; context.fillText(value.kind === "golden" ? "★" : LABELS[value.color], x + 26, y + 32); } if (value.kind === "line-h" || value.kind === "line-v") { if (art?.line) { context.save(); context.translate(x + 26, y + 26); if (value.kind === "line-v") context.rotate(Math.PI / 2); context.drawImage(art.line, -20, -20, 40, 40); context.restore(); } else { context.strokeStyle = "white"; context.lineWidth = 3; context.beginPath(); if (value.kind === "line-h") { context.moveTo(x + 9, y + 26); context.lineTo(x + 43, y + 26); } else { context.moveTo(x + 26, y + 9); context.lineTo(x + 26, y + 43); } context.stroke(); } } }; shown.current.forEach((value, index) => { if (value && !active.has(index)) { const at = point(index); tile(value, at.x, at.y); } }); moving.current.forEach((item) => { const from = point(item.from); const to = point(item.to); tile(item.tile, from.x + (to.x - from.x) * item.progress, from.y + (to.y - from.y) * item.progress); }); const marked = selected.current ?? cursor; const mark = point(marked); context.strokeStyle = selected.current === null ? "rgba(255,226,120,.75)" : "#ffe278"; context.lineWidth = 3; context.strokeRect(mark.x + 3, mark.y + 3, 46, 46); if (!disabled) { const hint = findHint(engine); if (hint) hint.forEach((index) => { const at = point(index); context.strokeStyle = "#fff"; context.lineWidth = 2; context.strokeRect(at.x + 7, at.y + 7, 38, 38); }); } if (art?.board) context.drawImage(art.board, 28, 28, 456, 456); }, [cursor, disabled, engine]);
  drawRef.current = draw;
  useEffect(() => { let alive = true; void loadFootballMatch3Assets().then((value) => { if (alive) { const transparent = document.createElement("canvas"); transparent.width = 1; transparent.height = 1; assets.current = { ...value, background: transparent as unknown as HTMLImageElement }; drawRef.current(); } }); return () => { alive = false; }; }, []);
  useEffect(() => { const canvas = canvasRef.current; const context = canvas?.getContext("2d"); if (!canvas || !context) return; const resize = () => { const rect = canvas.getBoundingClientRect(); const dpr = devicePixelRatio || 1; canvas.width = Math.max(1, Math.round(rect.width * dpr)); canvas.height = Math.max(1, Math.round(rect.height * dpr)); const scale = canvas.height / 512; context.setTransform(scale, 0, 0, scale, (canvas.width - canvas.height) / 2, 0); drawRef.current(); }; const observer = new ResizeObserver(resize); observer.observe(canvas); resize(); return () => observer.disconnect(); }, []);
  useEffect(() => { if (!steps.length && !invalidSwap) { shown.current = copy(engine.board); moving.current = []; draw(); return; } let cancelled = false; let frame = 0; const reduced = matchMedia("(prefers-reduced-motion: reduce)").matches; const pause = (ms: number) => new Promise<void>((resolve) => window.setTimeout(resolve, reduced ? 45 : ms)); const animate = (a: number, b: number, backwards = false) => new Promise<void>((resolve) => { const first = shown.current[a]; const second = shown.current[b]; if (!first || !second) { resolve(); return; } moving.current = [{ from: a, to: b, tile: { ...first }, progress: backwards ? 1 : 0 }, { from: b, to: a, tile: { ...second }, progress: backwards ? 1 : 0 }]; const start = performance.now(); const tick = (now: number) => { const progress = Math.min(1, (now - start) / (reduced ? 55 : 180)); moving.current.forEach((item) => { item.progress = backwards ? 1 - progress : progress; }); draw(); if (progress < 1 && !cancelled) frame = requestAnimationFrame(tick); else resolve(); }; frame = requestAnimationFrame(tick); }); const run = async () => { shown.current = copy(animationBoard); if (invalidSwap) { await animate(...invalidSwap); if (!cancelled) await animate(...invalidSwap, true); moving.current = []; draw(); if (!cancelled) onAnimationEnd(); return; } for (const step of steps) { if (cancelled) return; if (step.swapped) { await animate(...step.swapped); if (cancelled) return; [shown.current[step.swapped[0]], shown.current[step.swapped[1]]] = [shown.current[step.swapped[1]], shown.current[step.swapped[0]]]; moving.current = []; draw(); await pause(45); } step.removed.forEach((index) => { shown.current[index] = null; }); step.created.forEach(({ index, tile }) => { shown.current[index] = { ...tile }; }); onClearStep(step); draw(); await pause(140); if (cancelled) return; const next = copy(shown.current); const falls = step.fall.map(({ from, to }) => ({ from, to, tile: shown.current[from] && { ...shown.current[from] } })).filter((entry): entry is { from: number; to: number; tile: Tile } => !!entry.tile); moving.current = falls.map((entry) => ({ ...entry, progress: 0 })); const start = performance.now(); await new Promise<void>((resolve) => { const tick = (now: number) => { const progress = Math.min(1, (now - start) / (reduced ? 55 : 230)); moving.current.forEach((item) => { item.progress = progress; }); draw(); if (progress < 1 && !cancelled) frame = requestAnimationFrame(tick); else resolve(); }; frame = requestAnimationFrame(tick); }); falls.forEach(({ from }) => { next[from] = null; }); falls.forEach(({ to, tile }) => { next[to] = tile; }); step.spawn.forEach(({ index, tile }) => { next[index] = { ...tile }; }); shown.current = next; moving.current = []; draw(); await pause(55); } if (!cancelled) onAnimationEnd(); }; void run(); return () => { cancelled = true; cancelAnimationFrame(frame); }; }, [animationBoard, draw, engine.board, invalidSwap, onAnimationEnd, onClearStep, steps]);
  const locate = (event: PointerEvent<HTMLCanvasElement>) => { const rect = event.currentTarget.getBoundingClientRect(); const x = Math.floor(((event.clientX - rect.left - (rect.width - rect.height) / 2) / rect.height * 512 - GRID_ORIGIN) / CELL_SIZE); const y = Math.floor(((event.clientY - rect.top) / rect.height * 512 - GRID_ORIGIN) / CELL_SIZE); return x >= 0 && x < 8 && y >= 0 && y < 8 ? y * 8 + x : null; };
  const dragNeighbor = (from: number, end: number) => { const fromRow = Math.floor(from / 8); const fromColumn = from % 8; const endRow = Math.floor(end / 8); const endColumn = end % 8; const horizontal = Math.abs(endColumn - fromColumn) >= Math.abs(endRow - fromRow); const candidate = horizontal ? from + (endColumn > fromColumn ? 1 : -1) : from + (endRow > fromRow ? 8 : -8); return candidate >= 0 && candidate < 64 && (horizontal ? Math.floor(candidate / 8) === fromRow : true) ? candidate : null; };
  const choose = (index: number) => { if (disabled) return; if (selected.current !== null && Math.abs(Math.floor(selected.current / 8) - Math.floor(index / 8)) + Math.abs(selected.current % 8 - index % 8) === 1) { onTryMove(selected.current, index); selected.current = null; } else selected.current = selected.current === index ? null : index; setCursor(index); draw(); };
  return <canvas ref={canvasRef} className="football-match3-canvas" tabIndex={0} aria-label="축구 매치3 퍼즐 보드" onPointerDown={(event) => { pointer.current = locate(event); event.currentTarget.setPointerCapture(event.pointerId); }} onPointerUp={(event) => { const end = locate(event); if (pointer.current !== null && end !== null && pointer.current !== end && !disabled) { const neighbor = dragNeighbor(pointer.current, end); if (neighbor !== null) onTryMove(pointer.current, neighbor); selected.current = null; } else if (end !== null) choose(end); pointer.current = null; }} onKeyDown={(event) => { if (disabled) return; const delta: Record<string, number | undefined> = { ArrowLeft: -1, ArrowRight: 1, ArrowUp: -8, ArrowDown: 8 }; if (event.key === " ") { event.preventDefault(); selected.current = selected.current === null ? cursor : null; draw(); return; } const amount = delta[event.key]; if (amount === undefined) return; event.preventDefault(); const next = cursor + amount; if (next < 0 || next >= 64 || (Math.abs(amount) === 1 && Math.floor(next / 8) !== Math.floor(cursor / 8))) return; if (selected.current !== null) { onTryMove(selected.current, next); selected.current = null; } setCursor(next); draw(); }} />;
}
